#!/bin/bash
# Quick Reference for Remote Host Automation
# Copy this to your shell alias or bookmark

echo "════════════════════════════════════════════════════════════════"
echo "Multi-Host Automation Quick Reference"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "MASTER CONTROL:"
echo "  orchestrate.sh check-all        # Check all hosts"
echo "  orchestrate.sh health-all       # Detailed health check"
echo "  orchestrate.sh status-all       # Container status"
echo "  orchestrate.sh sync-all         # Backup & download configs"
echo "  orchestrate.sh push-all         # Upload changes"
echo "  orchestrate.sh start-all        # Start all services"
echo "  orchestrate.sh stop-all         # Stop all services"
echo ""
echo "TAMMEDIABOX (192.168.0.13):"
echo "  orchestrate.sh tmb check        # Connectivity check"
echo "  orchestrate.sh tmb ps           # Container status"
echo "  orchestrate.sh tmb logs [svc]   # View logs"
echo "  orchestrate.sh tmb restart      # Restart services"
echo "  orchestrate.sh tmb health       # Health check"
echo ""
echo "AI_DOCKER_HOST (192.168.0.7):"
echo "  orchestrate.sh ai check         # Connectivity check"
echo "  orchestrate.sh ai health        # Health + GPU status"
echo "  orchestrate.sh ai ps ollama     # Container status"
echo "  orchestrate.sh ai logs ollama   # Ollama logs"
echo "  orchestrate.sh ai start ollama  # Start LLM stack"
echo "  orchestrate.sh ai start paperless # Start document management"
echo ""
echo "SETUP:"
echo "  setup-cron.sh                   # Install automated cron jobs"
echo ""
echo "LOGS:"
echo "  /opt/stacks/TamMediaBox/sync.log"
echo "  /opt/stacks/AI_Docker_Host/sync.log"
echo "  /var/log/stacks/health-check.log"
echo "════════════════════════════════════════════════════════════════"
